version: "2"

services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "8081:8080"
    volumes:
      - git-volume:/var/gerrit/git
      - db-volume:/var/gerrit/db
      - index-volume:/var/gerrit/index
      - cache-volume:/var/gerrit/cache
  sonarqube:
    image: sonarqube
    ports: 
      - "9092:9092"
      - "9000:9000"
    
volumes:
  git-volume:
  db-volume:
  index-volume:
  cache-volume:
